query categories {
  categories(pageSize: 0, page: 0, term: "")
    @context(provider: "vtex.catalog-graphql") {
    items {
      label:name
      value:id
      hasChildrenCategories
      order
      fatherCategoryId
    }
  }
}
