mutation updateConf($configuration: ConfigurationInput!) {
  updateConfiguration(configuration: $configuration) {
    id
    name
    status
    type
    value
    created_at
    updated_at
    sellers
    ean
    productRef
    productName
    skuRef
    skuName
    brand
    category
    restrictionStatus
    restrictionList
  }
}
